### PR TITLE
Authentication_devise

### PR DESCRIPTION
**Pull request by billodiallo**
Second review
we completed all the requirements things
 
In this Pull request we Created a Member & Post model
- Created a Post controller
- Created view pages for member, post & index
- Create migration files with table rules
- Add devise to user for Authentication (sign_in ,sign_up)
- Adjust associations between models
- Create migration files with required foreign keys

### CODE REVIEW

**Review by andresporras3423 — CHANGES_REQUESTED** [review]
### Status: Changes Required :recycle:
**Hello  Billo Diallo [status: Enrolled] & Denis Diaconu** 
Good job with your first submission for this project :muscle:  :muscle:
There are some improvements to do before you can go ahead:

- [x] Remove commented code in application.html.erb
- [x] Add rspec unit and integration tests to your project
- [x] sing_up isn't working


 
Please request another review once you are ready! :+1: 
 
Happy coding :relaxed:
 
Oscar Andrés Russi Porras

**Comment by billodiallo** [comment]
Thanks for your review, sign_up is working fine , remove the comment line and fix the linters errors and rubocop

**Review by whiz25 — CHANGES_REQUESTED** [review]
## Changes Required 🙏🏿 
Nice work making the requested changes. I was able to signup, create a post. Well done.
Let's work on the testing part. You don't have a `spec` folder but a `test` folder with test cases. And running `rspec` doesn't execute test cases. 
You need to run `rspec --init` then move unit tests to the `spec` folder from `test`.


### Martin Afani
#### Slack: whiz25

**Comment by billodiallo** [comment]
Hello Guys
The rspec testing is not a part of requirements .
kindly your colleague reviewer for confirmation.
Thanks for your review.

**Review by oloomoses — APPROVED** [review]
# Congratulations, Project Approved. :muscle: :tada: :clap: 
**Great job working on the suggested changes from the previous review.
You have passed all the requirements for this project :muscle: 
Feel free to merge and close this pull request.**

**I wish you the best in your next project and see you at the top :rocket:** 
#### Happy Coding
_Slack: Oloo Moses_

**Pull request merged**
